server:
  port: 8080
spring:
  application:
    name: WebProServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memoir
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: 56d3ac2c3a9fc538368090120ca204c496e17f929ff1c69b93881eda038b2279
      expiration: 86400000 # A day
      refresh-token:
        expiration: 604800000 # 7 days