server:
  port: 8080

spring:
  profiles:
    include: prod

  application:
    name: memoirServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:demo}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:1234}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      format_sql: true

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME:my-bucket}
        region: ${AWS_REGION:my-region}

      region:
        static: ${AWS_REGION:my-region}

      credentials:
        access-key: ${S3_ACCESS:my-access}
        secret-key: ${S3_SECRET:my-secret}

secret:
  secret-key: ${SECRET_KEY:asdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfdsasdfghgfds}
  access-exp: ${ACCESS_EXP:3600}
  refresh-exp: ${REFRESH_EXP:1205600}
